version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '09:00'
  open-pull-requests-limit: 10
  versioning-strategy: increase
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: '09:00'
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
