require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
  NewCops: enable

Layout/LineLength:
  Exclude:
    - 'config/application.rb'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/puma.rb'
    - 'Rakefile'
    - 'spec/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'config/initializers/content_security_policy.rb'
    - 'config/routes.rb'
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Security/Eval:
  Exclude:
    - 'app/controllers/challenges_controller.rb'

Style/Documentation:
  Exclude:
    - 'app/controllers/*'
    - 'db/migrate/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
