require: rubocop-performance

Rails:
  Enabled: true

AllCops:
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "node_modules/**/*"

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production

Documentation:
  Exclude:
    - "app/controllers/*"
    - "db/migrate/*"

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*"

Metrics/BlockLength:
  Exclude:
    - "config/environments/*"
    - "config/routes.rb"
    - "spec/**/*"

Metrics/LineLength:
  Exclude:
    - "config/application.rb"
    - "config/environments/*"
    - "config/initializers/*"
    - "config/puma.rb"
    - "Rakefile"
    - "spec/*"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"

Security/Eval:
  Exclude:
    - "app/controllers/challenges_controller.rb"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
