Documentation:
  Exclude:
    - "app/controllers/*"
    - "db/migrate/*"

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*"

Metrics/BlockLength:
  Exclude:
    - "config/environments/*"
    - "db/schema.rb"
    - "spec/**/*"

Metrics/LineLength:
  Exclude:
    - "db/schema.rb"
    - "config/application.rb"
    - "config/environments/*"
    - "config/initializers/*"
    - "config/puma.rb"
    - "Rakefile"
    - "spec/*"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
