language: ruby
rvm:
  - 2.4.0

services:
  - postgresql

before_install:
  - gem update --system

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
