version: 2
jobs:
  build:
    parallelism: 4
    working_directory: ~/hackergateway
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
          RUBYOPT: -W:no-deprecated
      - image: circleci/postgres:12.2
        environment:
          POSTGRES_DB: HackerGateway_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          key: hackergateway-bundle-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: hackergateway-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Restore yarn / webpacker cache
      - restore_cache:
          keys:
            - hackergateway-yarn-{{ checksum "yarn.lock" }}
            - hackergateway-yarn-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / webpacker cache
      - save_cache:
          key: hackergateway-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      # Run rspec in parallel
      - type: shell
        command: >
          bundle exec rspec
          --profile
          --out test_results/rspec.xml
          $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save test results for timing analysis
      - store_test_results:
          path: test_results
